FROM golang:1.9.2-alpine

MAINTAINER Ming-Jui Chen <cutedogspark@gmail.com>

RUN apk update \
  && apk add git make curl perl bash build-base && rm -rf /var/cache/apk/*

RUN curl https://glide.sh/get | sh && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -u github.com/golang/protobuf/protoc-gen-go

WORKDIR $GOPATH
